import numpy as np
import random
my_array=np.arange(8)
print(my_array)
print(type(my_array))
my_array=np.arange(2,8)
print(my_array)
my_array=np.arange(2,8,2)
print(my_array)
from_list=np.array([1,2,3,4])
print(from_list)
from_list=np.array([[1,2,3,4],
                    [4,5,6,7]])
print(from_list)
twoD=np.array((np.arange(1,8,3),np.arange(2,9,3)))
print(twoD)
print(twoD.shape)
twoD=twoD.reshape(3,2)
print(twoD)
twoD=twoD.reshape(6)
print(twoD)
twoD=twoD.reshape((2,1,3))
print(twoD)
empty_array=np.zeros((2,2))
print(empty_array)
empty_array=np.ones((2,2))
print(empty_array)
eye_array=np.eye(4)
print(eye_array)
eye_array=np.eye(4,k=-1)
print(eye_array)
eye_array[eye_array==0]=2
print(eye_array)
eye_array[eye_array<6]=3
print(eye_array)
eye_array[0]=5
print(eye_array)
eye_array[:2]=7
print(eye_array)
eye_array[:,1]=9
print(eye_array)
eye_array[:,-1]=12
print(eye_array)
sorrt=np.sort(eye_array,axis=1)
print(sorrt)
sorrt=np.sort(eye_array,axis=0)
print(sorrt)
my_list=[1,2,3,4,5,6,7,8,9]
print(random.choice(my_list))
print(random.randrange(25,50))
print(my_array.size)
print(my_array.T)
